# Generated by Django 4.2.5 on 2023-09-15 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0003_product_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carousel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(max_length=120)),
                ('caption', models.CharField(max_length=120)),
                ('image', models.ImageField(blank=True, null=True, upload_to='carousel/')),
            ],
        ),
    ]
