# Generated by Django 4.2.5 on 2023-10-30 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0004_contactrequest_delete_customerprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactrequest',
            name='subject',
            field=models.CharField(choices=[('Order issues', 'Order status'), ('Product question', 'Product question'), ('Report an issue', 'Report an issue'), ('Request refund or discount', 'Request refund or discount'), ('Feedback', 'Feedback'), ('Other', 'Other')], max_length=255),
        ),
    ]
